// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.0 (Build Build 232 06/12/2013)
// Created on Sun Feb 15 19:53:13 2015

led_ctrl_free_fall led_ctrl_free_fall_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.led_en(led_en_sig) ,	// input  led_en_sig
	.height(height_sig) ,	// input [3:0] height_sig
	.col(col_sig) ,	// output [7:0] col_sig
	.row(row_sig) ,	// output [7:0] row_sig
	.led_prepared(led_prepared_sig) 	// output  led_prepared_sig
);

defparam led_ctrl_free_fall_inst.frame_time = 'b00000000100110001001011010000000;
//defparam led_ctrl_free_fall_inst.hold_time = ;
//defparam led_ctrl_free_fall_inst.remain_time = ;
//defparam led_ctrl_free_fall_inst.fall_1_time = ;
//defparam led_ctrl_free_fall_inst.fall_2_time = ;
//defparam led_ctrl_free_fall_inst.fall_3_time = ;
//defparam led_ctrl_free_fall_inst.fall_4_time = ;
//defparam led_ctrl_free_fall_inst.fall_5_time = ;
//defparam led_ctrl_free_fall_inst.fall_6_time = ;
//defparam led_ctrl_free_fall_inst.fall_7_time = ;
defparam led_ctrl_free_fall_inst.ws = 'b100;
defparam led_ctrl_free_fall_inst.ms = 'b1000;
defparam led_ctrl_free_fall_inst.ch = 'b1000;
